In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("patient_health_data.csv")

In [3]:
df.head()

   age        bmi  blood_pressure  cholesterol  ...  diet_quality  smoking_status  alcohol_intake  health_risk_score
0   58  24.865215      122.347094   165.730375  ...      7.675409              No        0.824123         150.547752
1   71  19.103168      136.852028   260.610781  ...      8.933057              No        0.852910         160.320350
2   48  22.316562      137.592457   177.342582  ...      3.501119             Yes        4.740542         187.487398
3   34  22.196893      153.164775   234.594764  ...      2.745585              No        2.226231         148.773138
4   62  29.837173       92.768973   276.106498  ...      8.918348              No        3.944011         170.609655

[5 rows x 12 columns]

In [4]:
df.isna().sum()

age                  0
bmi                  0
blood_pressure       0
cholesterol          0
glucose              0
insulin              0
heart_rate           0
activity_level       0
diet_quality         0
smoking_status       0
alcohol_intake       0
health_risk_score    0
dtype: int64

In [7]:
df["smoking_status"]= df["smoking_status"].apply(lambda x: 1 if x == "Yes" else 0)

In [8]:
df

     age        bmi  blood_pressure  cholesterol  ...  diet_quality  smoking_status  alcohol_intake  health_risk_score
0     58  24.865215      122.347094   165.730375  ...      7.675409               0        0.824123         150.547752
1     71  19.103168      136.852028   260.610781  ...      8.933057               0        0.852910         160.320350
2     48  22.316562      137.592457   177.342582  ...      3.501119               1        4.740542         187.487398
3     34  22.196893      153.164775   234.594764  ...      2.745585               0        2.226231         148.773138
4     62  29.837173       92.768973   276.106498  ...      8.918348               0        3.944011         170.609655
..   ...        ...             ...          ...  ...           ...             ...             ...                ...
245   73  33.923019      154.961623   239.257347  ...      1.837274               0        3.200992         162.542038
246   51  18.666168       83.047215   200.890687  ...      1.264277               0        1.492175         136.146456
247   51  25.105083      166.721498   235.416528  ...      8.406626               0        1.201912         156.758986
248   43  34.448869      115.414667   283.119072  ...      2.887777               0        1.559495         204.649145
249   60  27.315522      119.716383   233.508238  ...      4.411244               1        1.280238         106.408929

[250 rows x 12 columns]

In [12]:
X = df.drop(["health_risk_score"],axis=1)
y = df["health_risk_score"]

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.25,random_state=11)

In [18]:
lm = LinearRegression()
lm.fit(X_train,y_train)
lm.score(X_test,y_test)

0.8274453995158204

In [26]:
alpha = [0.001,0.01, 0.1, 1.0,10,100,1000]

In [27]:
for al in alpha:
    lasso = Lasso(alpha=al)
    lasso.fit(X_train,y_train)
    score = lasso.score(X_test,y_test)
    print(f'for alpha {al} score is {score}')

for alpha 0.001 score is 0.8274471772448038
for alpha 0.01 score is 0.8274621491584028
for alpha 0.1 score is 0.8276304434139139
for alpha 1.0 score is 0.8285686013599195
for alpha 10 score is 0.78460935785216
for alpha 100 score is 0.577918419344478
for alpha 1000 score is -0.0427326705634008

In [28]:
for al in alpha:
    ridge = Ridge(alpha=1.0)
    ridge.fit(X_train,y_train)
    score = ridge.score(X_test,y_test)
    print(f'for alpha {al} score is {score}')

for alpha 0.001 score is 0.8275454647161337
for alpha 0.01 score is 0.8275454647161337
for alpha 0.1 score is 0.8275454647161337
for alpha 1.0 score is 0.8275454647161337
for alpha 10 score is 0.8275454647161337
for alpha 100 score is 0.8275454647161337
for alpha 1000 score is 0.8275454647161337